name: Build workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set gradle permissions
        run: sudo chmod +x ./gradlew
      - name: Download dependencies
        run: |
          ./gradlew dependencies

      - name: Build debug
        run: |
          ./gradlew assembleLocalDebug

      - name: Test debug
        run: |
          ./gradlew testLocalDebugUnitTest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        if: github.ref == 'refs/heads/master'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set gradle permissions
        if: github.ref == 'refs/heads/master'
        run: sudo chmod +x ./gradlew

      - name: Deploy artifacts
        if: github.ref == 'refs/heads/master'
        run: |
          ./gradlew uploadArchives
          ./gradlew uploadArchives -Psnapshot=true
          git add .
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"