name: Build workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set gradle permissions
      run: sudo chmod +x android-app/gradlew
    - name: Download dependencies
      run: |
        ./gradlew app:dependencies

    - name: Build debug
      run: |
        ./gradlew assembleDebug
    
    - name: Test debug
      run: |
        ./gradlew testDebugUnitTest
 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set gradle permissions
      run: sudo chmod +x android-app/gradlew
      
    - name : Deploy artifacts
      run: |
        ./gradlew uploadArchives
        ./gradlew uploadArchives -Psnapshot=true
        git add .
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
     - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

